### PR TITLE
Added region-controls image, and changed rectangle control button to use...

### PR DESCRIPTION
**Pull request by hasimpson-usgs**
... the image.  Also enabled the rectangle control by default.

### CODE REVIEW

**Comment by jmfee-usgs** [comment]
- enable by default should be an option, and event pages should use that option.
- when I open the region view example, clear the region, then show the region view, the control is enabled but the icon doesn't appear to be enabled and the instructions are not shown.

**Comment by hasimpson-usgs** [comment]
Was unable to add enable by default as option.  Instead the user should call the enable function during show. Change regionView to call enable function when data is null.  
Also,  need to change earthquake-event-ws to move the instantiation of the regionView,  inside the button listener.   
Finally,  ran into a probably known race-condition in leaflet,  added a wait.

**Comment by emartinez-usgs** [comment]
- Do not always call enable method on show.
- Use an option to ```RegionView.show``` method to force enable rectangle control.
  - Augment this option with the existence of a valid region parameter.
  - Call ```_rectangleControl.enable``` if the new option is true.
  - This option should be specific to the rectangle control. Recall the region view will eventually support circle and polygon regions as well, so a generic "enable" will not be sufficient.
- Timeout should probably be 0 seconds. The trick to the timeout is to push a new event onto the [event loop](https://developer.mozilla.org/en-US/docs/Web/JavaScript/EventLoop) rather than running inline.
- Timeout callback need not be bound.

**Comment by emartinez-usgs** [comment]
- Do not use option to force-enable rectangle control on example page.
- The ```enableRectangleControl``` should be declared as part of the var statement, but should not be defined until after the input options are "sanitized".

**Pull request merged**
